-- =============================================================================
-- Poputi — одна полная схема Supabase (выполнить целиком в SQL Editor).
-- Идемпотентно: повторный запуск безопасен.
-- После применения: Settings → API → Reload schema (или подождать кэш PostgREST).
-- =============================================================================

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- 1. rides — заявки на карте / межгород (все поля, которые ждёт приложение)
-- -----------------------------------------------------------------------------
create table if not exists public.rides (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lat double precision,
  lng double precision,
  price integer not null default 0,
  type text not null default 'Passenger',
  from_location text,
  to_location text,
  name text,
  vk_id text,
  city text not null default 'Шумиха',
  status text not null default 'searching',
  comment text,
  partner_vk_id text,
  driver_id text,
  total_seats integer not null default 4,
  available_seats integer not null default 4,
  avatar text,
  car text,
  rating numeric(5, 2),
  trips integer,
  telegram text,
  seats integer
);

comment on table public.rides is 'Точки на карте и межгородские поездки';
comment on column public.rides.type is 'Driver | Passenger | City | Static | AdminPoint';
comment on column public.rides.status is 'searching | accepted | arrived | in_transit | completed | cancelled';
comment on column public.rides.city is 'Шумиха | Тюмень — фильтр в приложении';
comment on column public.rides.partner_vk_id is 'Второй участник (id123…), для отзыва';
comment on column public.rides.driver_id is 'vk_id (id123…) водителя';
comment on column public.rides.seats is 'Legacy; при наличии подтягивается в total/available_seats';

-- Догоняющие колонки, если таблица rides уже была создана раньше без части полей
alter table public.rides add column if not exists created_at timestamptz not null default now();
alter table public.rides add column if not exists lat double precision;
alter table public.rides add column if not exists lng double precision;
alter table public.rides add column if not exists price integer not null default 0;
alter table public.rides add column if not exists type text not null default 'Passenger';
alter table public.rides add column if not exists from_location text;
alter table public.rides add column if not exists to_location text;
alter table public.rides add column if not exists name text;
alter table public.rides add column if not exists vk_id text;
alter table public.rides add column if not exists city text;
alter table public.rides add column if not exists status text not null default 'searching';
alter table public.rides add column if not exists comment text;
alter table public.rides add column if not exists partner_vk_id text;
alter table public.rides add column if not exists driver_id text;
alter table public.rides add column if not exists total_seats integer not null default 4;
alter table public.rides add column if not exists available_seats integer not null default 4;
alter table public.rides add column if not exists avatar text;
alter table public.rides add column if not exists car text;
alter table public.rides add column if not exists rating numeric(5, 2);
alter table public.rides add column if not exists trips integer;
alter table public.rides add column if not exists telegram text;
alter table public.rides add column if not exists seats integer;

update public.rides set city = coalesce(nullif(trim(city), ''), 'Шумиха') where city is null;

do $fix_city$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public' and table_name = 'rides' and column_name = 'city'
  ) then
    alter table public.rides alter column city set default 'Шумиха';
    alter table public.rides alter column city set not null;
  end if;
end;
$fix_city$;

-- Normalize legacy status values
update public.rides set status = 'searching' where status is null or trim(status) = '' or status = 'open';
update public.rides set status = 'accepted' where status = 'in_progress';
alter table public.rides alter column status set default 'searching';

create index if not exists rides_city_created_idx on public.rides (city, created_at desc);
create index if not exists rides_vk_id_idx on public.rides (vk_id) where vk_id is not null;

-- Подтянуть legacy seats → total_seats / available_seats
do $seats_migration$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public' and table_name = 'rides' and column_name = 'seats'
  ) then
    update public.rides
    set
      total_seats = coalesce(nullif(seats, 0), total_seats),
      available_seats = coalesce(nullif(seats, 0), available_seats)
    where seats is not null;
  end if;
end;
$seats_migration$;

-- -----------------------------------------------------------------------------
-- 2. profiles — агрегаты по пользователю (vk_id вида id123456)
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  vk_id text primary key,
  total_rides integer not null default 0,
  average_rating numeric(3, 2) not null default 5.00,
  no_show_count integer not null default 0,
  avatar_url text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_updated_at_idx on public.profiles (updated_at desc);

alter table public.profiles add column if not exists no_show_count integer not null default 0;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists display_name text;

comment on table public.profiles is 'Кэш рейтинга/поездок для UI; average_rating синхронизируется из reviews в приложении';
comment on column public.profiles.avatar_url is 'URL фото пользователя из VK (photo_200)';
comment on column public.profiles.display_name is 'Имя Фамилия из VK';

-- -----------------------------------------------------------------------------
-- 3. reviews — отзывы после поездки
-- -----------------------------------------------------------------------------
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  ride_id bigint not null references public.rides (id) on delete cascade,
  reviewer_vk_id text not null,
  target_vk_id text not null,
  rating smallint not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (ride_id, reviewer_vk_id)
);

create index if not exists reviews_target_vk_id_idx on public.reviews (target_vk_id);
create index if not exists reviews_reviewer_vk_id_idx on public.reviews (reviewer_vk_id);

comment on table public.reviews is 'Один отзыв на ride_id от reviewer_vk_id';

-- -----------------------------------------------------------------------------
-- 4. ride_offers — торги водителей по городской заявке
-- -----------------------------------------------------------------------------
create table if not exists public.ride_offers (
  id bigint generated by default as identity primary key,
  ride_id bigint not null references public.rides (id) on delete cascade,
  driver_vk_id text not null,
  passenger_vk_id text not null,
  price integer not null default 0,
  price_delta integer not null default 0,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  driver_name text,
  driver_avatar text,
  driver_car text,
  driver_rating numeric(5, 2),
  pickup_eta_min integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ride_offers_ride_status_idx on public.ride_offers (ride_id, status);
create index if not exists ride_offers_passenger_status_idx on public.ride_offers (passenger_vk_id, status, created_at desc);
create unique index if not exists ride_offers_one_pending_per_driver
  on public.ride_offers (ride_id, driver_vk_id)
  where (status = 'pending');

comment on table public.ride_offers is 'Отклики/торги водителей по заявке пассажира';

-- -----------------------------------------------------------------------------
-- 4. bookings + RPC межгорода
-- -----------------------------------------------------------------------------
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  ride_id bigint not null references public.rides (id) on delete cascade,
  passenger_vk_id text not null,
  status text not null default 'booked' check (status in ('booked', 'no_show')),
  created_at timestamptz not null default now()
);

create index if not exists bookings_ride_id_idx on public.bookings (ride_id);
create index if not exists bookings_passenger_vk_id_idx on public.bookings (passenger_vk_id);

create unique index if not exists bookings_one_active_passenger_per_ride
  on public.bookings (ride_id, passenger_vk_id)
  where (status = 'booked');

create or replace function public.book_intercity_seat(p_ride_id bigint, p_passenger_vk_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_avail int;
  v_owner text;
begin
  select available_seats, vk_id into strict v_avail, v_owner from public.rides where id = p_ride_id for update;
  if v_owner is not null and v_owner = p_passenger_vk_id then
    return jsonb_build_object('ok', false, 'err', 'owner');
  end if;
  if v_avail < 1 then
    return jsonb_build_object('ok', false, 'err', 'no_seats');
  end if;

  insert into public.bookings (ride_id, passenger_vk_id, status)
  values (p_ride_id, p_passenger_vk_id, 'booked');

  update public.rides set available_seats = available_seats - 1 where id = p_ride_id;

  return jsonb_build_object('ok', true);
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'err', 'already');
  when no_data_found then
    return jsonb_build_object('ok', false, 'err', 'not_found');
end;
$$;

create or replace function public.mark_booking_no_show(p_booking_id bigint, p_driver_vk_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  b_ride_id bigint;
  b_passenger text;
  b_status text;
  owner_tag text;
begin
  select ride_id, passenger_vk_id, status into strict b_ride_id, b_passenger, b_status
  from public.bookings where id = p_booking_id for update;

  if b_status <> 'booked' then
    return jsonb_build_object('ok', false, 'err', 'bad_state');
  end if;

  select vk_id into strict owner_tag from public.rides where id = b_ride_id for update;
  if owner_tag <> p_driver_vk_id then
    return jsonb_build_object('ok', false, 'err', 'forbidden');
  end if;

  update public.bookings set status = 'no_show' where id = p_booking_id;
  update public.rides set available_seats = available_seats + 1 where id = b_ride_id;

  insert into public.profiles (vk_id, total_rides, average_rating, no_show_count)
  values (b_passenger, 0, 5.00, 1)
  on conflict (vk_id) do update
    set no_show_count = public.profiles.no_show_count + 1,
        updated_at = now();

  return jsonb_build_object('ok', true);
exception
  when no_data_found then
    return jsonb_build_object('ok', false, 'err', 'not_found');
end;
$$;

create or replace function public.accept_city_ride(p_ride_id bigint, p_driver_vk_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner text;
  v_partner text;
  v_status text;
  v_type text;
begin
  if nullif(trim(coalesce(p_driver_vk_id, '')), '') is null then
    return jsonb_build_object('ok', false, 'err', 'bad_driver');
  end if;

  select vk_id, partner_vk_id, status, type
    into strict v_owner, v_partner, v_status, v_type
  from public.rides
  where id = p_ride_id
  for update;

  if coalesce(v_type, '') <> 'City' then
    return jsonb_build_object('ok', false, 'err', 'not_city');
  end if;

  if coalesce(v_owner, '') = p_driver_vk_id then
    return jsonb_build_object('ok', false, 'err', 'owner');
  end if;

  if nullif(trim(coalesce(v_partner, '')), '') is not null then
    return jsonb_build_object('ok', false, 'err', 'already_taken');
  end if;

  if nullif(trim(coalesce(v_status, '')), '') is not null and v_status not in ('open', 'searching') then
    return jsonb_build_object('ok', false, 'err', 'not_open');
  end if;

  update public.rides
  set status = 'accepted',
      partner_vk_id = p_driver_vk_id,
      driver_id = p_driver_vk_id
  where id = p_ride_id;

  return jsonb_build_object('ok', true);
exception
  when no_data_found then
    return jsonb_build_object('ok', false, 'err', 'not_found');
end;
$$;

create or replace function public.accept_ride_offer(p_offer_id bigint, p_passenger_vk_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ride_id bigint;
  v_driver text;
  v_passenger text;
  v_price integer;
  v_ride_status text;
begin
  select ride_id, driver_vk_id, passenger_vk_id, price
    into strict v_ride_id, v_driver, v_passenger, v_price
  from public.ride_offers
  where id = p_offer_id and status = 'pending'
  for update;

  if v_passenger <> p_passenger_vk_id then
    return jsonb_build_object('ok', false, 'err', 'forbidden');
  end if;

  select status into strict v_ride_status
  from public.rides
  where id = v_ride_id and vk_id = p_passenger_vk_id
  for update;

  if coalesce(v_ride_status, 'searching') not in ('open', 'searching') then
    return jsonb_build_object('ok', false, 'err', 'not_open');
  end if;

  update public.ride_offers
  set status = 'accepted', updated_at = now()
  where id = p_offer_id;

  update public.ride_offers
  set status = 'rejected', updated_at = now()
  where ride_id = v_ride_id and id <> p_offer_id and status = 'pending';

  update public.rides
  set status = 'accepted',
      partner_vk_id = v_driver,
      driver_id = v_driver,
      price = v_price
  where id = v_ride_id;

  return jsonb_build_object('ok', true, 'ride_id', v_ride_id, 'driver_vk_id', v_driver);
exception
  when no_data_found then
    return jsonb_build_object('ok', false, 'err', 'not_found');
end;
$$;

grant execute on function public.book_intercity_seat(bigint, text) to anon, authenticated, service_role;
grant execute on function public.mark_booking_no_show(bigint, text) to anon, authenticated, service_role;
grant execute on function public.accept_city_ride(bigint, text) to anon, authenticated, service_role;
grant execute on function public.accept_ride_offer(bigint, text) to anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 5. Чаты
-- -----------------------------------------------------------------------------
create table if not exists public.chat_threads (
  id uuid primary key default gen_random_uuid(),
  vk_lower text not null,
  vk_higher text not null,
  last_message text not null default '',
  last_message_at timestamptz not null default now(),
  peer_labels jsonb not null default '{}'::jsonb,
  unique (vk_lower, vk_higher)
);

create index if not exists chat_threads_lower_idx on public.chat_threads (vk_lower);
create index if not exists chat_threads_higher_idx on public.chat_threads (vk_higher);
create index if not exists chat_threads_last_at_idx on public.chat_threads (last_message_at desc);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.chat_threads (id) on delete cascade,
  sender_vk_id text not null,
  body text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);
alter table public.chat_messages add column if not exists metadata jsonb;

create index if not exists chat_messages_thread_id_idx on public.chat_messages (thread_id, created_at);

comment on table public.chat_threads is 'Диалог 1:1; vk_lower < vk_higher лексикографически';
comment on column public.chat_threads.peer_labels is 'Подписи к vk_id для списка чатов';

-- -----------------------------------------------------------------------------
-- 6. Админка: бан пользователей
-- -----------------------------------------------------------------------------
create table if not exists public.banned_users (
  vk_id text primary key,
  display_name text,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists banned_users_created_at_idx on public.banned_users (created_at desc);

-- -----------------------------------------------------------------------------
-- 7. Оплата водителя (CloudTips; пишет сервер по service_role, RLS для anon)
-- -----------------------------------------------------------------------------
create table if not exists public.driver_payment_intents (
  invoice_id text primary key,
  vk_id text not null,
  layout_id text not null,
  status text not null default 'pending' check (status in ('pending', 'paid')),
  transaction_id text,
  amount numeric,
  currency text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists driver_payment_intents_vk_status_idx
  on public.driver_payment_intents (vk_id, status);

comment on table public.driver_payment_intents is 'Ожидание/подтверждение оплаты CloudTips по invoice_id';

alter table public.driver_payment_intents enable row level security;

-- -----------------------------------------------------------------------------
-- 7b. Оплата водителя через ЮKassa (24ч доступ к заявкам пассажиров)
-- -----------------------------------------------------------------------------
create table if not exists public.driver_access_payments (
  id bigint generated by default as identity primary key,
  vk_id text not null,
  yokassa_payment_id text not null unique,
  amount numeric not null,
  status text not null default 'pending' check (status in ('pending', 'paid')),
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  expires_at timestamptz
);

create index if not exists driver_access_payments_vk_status_idx
  on public.driver_access_payments (vk_id, status);

create index if not exists driver_access_payments_expires_idx
  on public.driver_access_payments (expires_at)
  where status = 'paid';

comment on table public.driver_access_payments is 'Оплата 24ч доступа водителей через ЮKassa';

alter table public.driver_access_payments enable row level security;

-- =============================================================================
-- 8. RLS (anon / authenticated)
-- Приложение использует publishable-ключ без Supabase Auth (нет auth.uid()).
-- Без политик INSERT/SELECT падают с «violates row-level security policy».
-- Политики открытые — как публичная доска; сужать доступ лучше через Edge Functions.
-- =============================================================================

-- rides
alter table public.rides enable row level security;
drop policy if exists rides_select_anon on public.rides;
create policy rides_select_anon on public.rides for select to anon, authenticated using (true);
drop policy if exists rides_insert_anon on public.rides;
create policy rides_insert_anon on public.rides for insert to anon, authenticated with check (true);
drop policy if exists rides_update_anon on public.rides;
create policy rides_update_anon on public.rides for update to anon, authenticated using (true) with check (true);
drop policy if exists rides_delete_anon on public.rides;
create policy rides_delete_anon on public.rides for delete to anon, authenticated using (true);

-- profiles
alter table public.profiles enable row level security;
drop policy if exists profiles_select_anon on public.profiles;
create policy profiles_select_anon on public.profiles for select to anon, authenticated using (true);
drop policy if exists profiles_insert_anon on public.profiles;
create policy profiles_insert_anon on public.profiles for insert to anon, authenticated with check (true);
drop policy if exists profiles_update_anon on public.profiles;
create policy profiles_update_anon on public.profiles for update to anon, authenticated using (true) with check (true);

-- reviews
alter table public.reviews enable row level security;
drop policy if exists reviews_select_anon on public.reviews;
create policy reviews_select_anon on public.reviews for select to anon, authenticated using (true);
drop policy if exists reviews_insert_anon on public.reviews;
create policy reviews_insert_anon on public.reviews for insert to anon, authenticated with check (true);

-- bookings (чтение списка пассажиров; RPC пишет от имени definer)
alter table public.bookings enable row level security;
drop policy if exists bookings_select_anon on public.bookings;
create policy bookings_select_anon on public.bookings for select to anon, authenticated using (true);

-- ride_offers
alter table public.ride_offers enable row level security;
drop policy if exists ride_offers_select_anon on public.ride_offers;
create policy ride_offers_select_anon on public.ride_offers for select to anon, authenticated using (true);
drop policy if exists ride_offers_insert_anon on public.ride_offers;
create policy ride_offers_insert_anon on public.ride_offers for insert to anon, authenticated with check (true);
drop policy if exists ride_offers_update_anon on public.ride_offers;
create policy ride_offers_update_anon on public.ride_offers for update to anon, authenticated using (true) with check (true);

-- чаты
alter table public.chat_threads enable row level security;
drop policy if exists chat_threads_select_anon on public.chat_threads;
create policy chat_threads_select_anon on public.chat_threads for select to anon, authenticated using (true);
drop policy if exists chat_threads_insert_anon on public.chat_threads;
create policy chat_threads_insert_anon on public.chat_threads for insert to anon, authenticated with check (true);
drop policy if exists chat_threads_update_anon on public.chat_threads;
create policy chat_threads_update_anon on public.chat_threads for update to anon, authenticated using (true) with check (true);
drop policy if exists chat_threads_delete_anon on public.chat_threads;
create policy chat_threads_delete_anon on public.chat_threads for delete to anon, authenticated using (true);

alter table public.chat_messages enable row level security;
drop policy if exists chat_messages_select_anon on public.chat_messages;
create policy chat_messages_select_anon on public.chat_messages for select to anon, authenticated using (true);
drop policy if exists chat_messages_insert_anon on public.chat_messages;
create policy chat_messages_insert_anon on public.chat_messages for insert to anon, authenticated with check (true);
drop policy if exists chat_messages_update_anon on public.chat_messages;
create policy chat_messages_update_anon on public.chat_messages for update to anon, authenticated using (true) with check (true);

-- админка банов (тот же anon-клиент в браузере)
alter table public.banned_users enable row level security;
drop policy if exists banned_users_select_anon on public.banned_users;
create policy banned_users_select_anon on public.banned_users for select to anon, authenticated using (true);
drop policy if exists banned_users_insert_anon on public.banned_users;
create policy banned_users_insert_anon on public.banned_users for insert to anon, authenticated with check (true);
drop policy if exists banned_users_delete_anon on public.banned_users;
create policy banned_users_delete_anon on public.banned_users for delete to anon, authenticated using (true);

-- driver_payment_intents: только service_role (политик для anon нет — так и задумано)

-- =============================================================================
-- 9. Realtime — включить для таблиц, где нужны подписки
-- =============================================================================
-- Выполните в SQL Editor если Realtime не включён автоматически:
-- alter publication supabase_realtime add table public.rides;
-- alter publication supabase_realtime add table public.chat_messages;
-- alter publication supabase_realtime add table public.chat_threads;
